# Site settings
title: Heatherfield Foods Inc.
tag_text: Solo
description: Welcome to the Heatherfield Foods family of products. For over 25 years we have brought you quality foods. Please visit our websites to learn more.
url: "http://adrianmiller.design/heatherfield-foods"

# Build settings
markdown: kramdown

exclude: ["README.md"]

# SASS Dir
sass:
    sass_dir: assets